# ---------------------------------------------------------
#   ログイン情報
# ---------------------------------------------------------

[user]

# ニコニコのログインアカウント
mail = "xxxxxxxxx@sample.com"

# ニコニコのログインパスワード
password = "xxxxxxxxxx"


# ---------------------------------------------------------
#   集計パラメータ
# ---------------------------------------------------------

[counter]

# 集計を開始する時刻
start = "2018-02-09 21:00:00"

# 集計を終了する時刻
end = "2018-02-26 21:00:00"

# 集計対象となる動画を登録したマイリストのID
# ここで指定したマイリストから動画IDを取得し、videos.txt を生成する
# videos.csv が既に存在する場合はスキップされる
mylist = [ 60232979 ]

# 入出力ファイルの文字コード
# 初期値 "cp932" は Excel との互換性のため
# cp932 の場合、サポートされていない文字は &#nnn; 形式の XML 文字参照に置換される
# Excel を使用しないならば、設定を "utf-8" に変更することを推奨
encoding = "cp932"


# ---------------------------------------------------------
#   HTTP接続パラメータ
# ---------------------------------------------------------

[http]

# 連続でサーバーに接続する間隔(ミリ秒)
interval = 1000

# サーバーエラー発生時の待機時間(ミリ秒)
server_error_interval = 30000

# 通信失敗時の再試行回数
retry = 4


# ---------------------------------------------------------
#   ログ
# ---------------------------------------------------------

[logging]

# FATAL, ERROR, WARNING, INFO, DEBUG
level = "INFO"
format = "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
